import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
          name: 'Quincy',
          email: 'admin@example.com',
          password: bcrypt.hashSync('123456@'),
          isAdmin: true,
        },
        {
          name: 'Khanh',
          email: 'user@example.com',
          password: bcrypt.hashSync('123456@'),
          isAdmin: false,
        },
      ],
    products: [
        {
            // _id: '1',
            name: 'Iphone 14 promax',
            slug: 'iphone-14promax',
            category: 'iphone',
            image: '/images/p1.jpg',
            price: 1200,
            countInStock: 10,
            brand: 'apple',
            rating: 5.0,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            // _id: '2',
            name: 'Iphone 14 pro',
            slug: 'iphone-14pro',
            category: 'iphone',
            image: '/images/p2.jpg',
            price: 1100,
            countInStock: 0,
            brand: 'apple',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            // _id: '3',
            name: 'Iphone 14',
            slug: 'iphone-14',
            category: 'iphone',
            image: '/images/p3.jpg',
            price: 1000,
            countInStock: 30,
            brand: 'apple',
            rating: 4.0,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            // _id: '4',
            name: 'iphone 13 promax',
            slug: 'iphone-13promax',
            category: 'iphone',
            image: '/images/p4.jpg',
            price: 800,
            countInStock: 10,
            brand: 'apple',
            rating: 5.0,
            numReviews: 12,
            description: '6.7" Super Retina XDR display, A15 Bionic chip, 5G connectivity, Pro camera system, and Ceramic Shield front cover.',
        },
        {
            name: 'iphone 13 pro',
            slug: 'iphone-13pro',
            category: 'iphone',
            image: '/images/p4.jpg',
            price: 700,
            countInStock: 10,
            brand: 'apple',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'iphone 13',
            slug: 'iphone-13',
            category: 'iphone',
            image: '/images/p4.jpg',
            price: 700,
            countInStock: 10,
            brand: 'apple',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'iphone 12 promax',
            slug: 'iphone-12promax',
            category: 'iphone',
            image: '/images/p4.jpg',
            price: 700,
            countInStock: 10,
            brand: 'apple',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'iphone 12 pro',
            slug: 'iphone-12pro',
            category: 'iphone',
            image: '/images/p4.jpg',
            price: 600,
            countInStock: 10,
            brand: 'apple',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'iphone 12',
            slug: 'iphone-12',
            category: 'iphone',
            image: '/images/p4.jpg',
            price: 500,
            countInStock: 10,
            brand: 'apple',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Samsung Galaxy S23',
            slug: 'samsung-galaxy-s23',
            category: 'samsung',
            image: '/images/p4.jpg',
            price: 1100,
            countInStock: 10,
            brand: 'samsung',
            rating: 5.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Samsung Galaxy S22',
            slug: 'samsung-galaxy-s22',
            category: 'samsung',
            image: '/images/p4.jpg',
            price: 1000,
            countInStock: 10,
            brand: 'samsung',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Samsung Galaxy S21',
            slug: 'samsung-galaxy-s21',
            category: 'samsung',
            image: '/images/p4.jpg',
            price: 900,
            countInStock: 10,
            brand: 'samsung',
            rating: 4.5,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Samsung Galaxy S20',
            slug: 'samsung-galaxy-s20',
            category: 'samsung',
            image: '/images/p4.jpg',
            price: 800,
            countInStock: 10,
            brand: 'samsung',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Xiaomi redmi note 11 pro',
            slug: 'xiaomi-redmi-note-11pro',
            category: 'xiaomi',
            image: '/images/p4.jpg',
            price: 500,
            countInStock: 10,
            brand: 'xiaomi',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Xiaomi redmi note 11s',
            slug: 'xiaomi-redmi-note-11s',
            category: 'xiaomi',
            image: '/images/p4.jpg',
            price: 450,
            countInStock: 10,
            brand: 'xiaomi',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Xiaomi redmi note 11',
            slug: 'xiaomi-redmi-note-11',
            category: 'xiaomi',
            image: '/images/p4.jpg',
            price: 450,
            countInStock: 10,
            brand: 'xiaomi',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Xiaomi 13',
            slug: 'xiaomi-13',
            category: 'xiaomi',
            image: '/images/p4.jpg',
            price: 450,
            countInStock: 10,
            brand: 'xiaomi',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Xiaomi 13 Lite',
            slug: 'xiaomi-13lite',
            category: 'xiaomi',
            image: '/images/p4.jpg',
            price: 450,
            countInStock: 10,
            brand: 'xiaomi',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Oppo reno8 T',
            slug: 'oppo-reno8-t',
            category: 'oppo',
            image: '/images/p4.jpg',
            price: 550,
            countInStock: 10,
            brand: 'oppo',
            rating: 4.5,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Oppo reno8 series',
            slug: 'oppo-reno8-series',
            category: 'oppo',
            image: '/images/p4.jpg',
            price: 550,
            countInStock: 10,
            brand: 'oppo',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Oppo reno7',
            slug: 'oppo-reno7',
            category: 'oppo',
            image: '/images/p4.jpg',
            price: 400,
            countInStock: 10,
            brand: 'oppo',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'sony xperia 1 mark 3',
            slug: 'sony-xperia-1mark3',
            category: 'sony',
            image: '/images/p4.jpg',
            price: 1050,
            countInStock: 10,
            brand: 'sony',
            rating: 5.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'sony xperia 5 mark 3',
            slug: 'sony-xperia-5mark3',
            category: 'sony',
            image: '/images/p4.jpg',
            price: 950,
            countInStock: 10,
            brand: 'sony',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            name: 'Bphone A40',
            slug: 'Bphone-A40',
            category: 'bphone',
            image: '/images/p4.jpg',
            price: 250,
            countInStock: 10,
            brand: 'bphone',
            rating: 3.0,
            numReviews: 12,
            description: 'immediate quality product',
        },
        {
            name: 'Bphone A50',
            slug: 'Bphone-A50',
            category: 'bphone',
            image: '/images/p4.jpg',
            price: 350,
            countInStock: 10,
            brand: 'bphone',
            rating: 3.5,
            numReviews: 12,
            description: 'immediate quality product',
        }
    ]
};

export default data;